# Site settings
title: "Sound Security Podcast"
email: "info@soundsecurity.io"
description: "Braxton Ehle and Osman Surkatty rant about the latest in information security news to help enterprises and mere mortals defend their information."
baseurl: ""
url: "https://soundsecurity.io"
url_http: "http://soundsecurity.io"
username: "braxtone"
twitter_username: "soundsec"
gitrepo: "https://github.com/braxtone/soundsecurity"

# Build settings
exclude: [
          "LICENSE", 
          "README.md", 
          "bin/", 
          "_drafts/1969-07-16-template.markdown", 
          "s3_website.yml", 
          "spec/",
          "Rakefile",
          "Gemfile*",
          "_posts/template.markdown"
         ]

markdown: kramdown
permalink: pretty
show_drafts: null

# Podcast metadata
copyright: "2015 Braxton Ehle + Osman Surkatty"
subtitle: "Fanfare for the common infosec ninja"
author: "Sound Security"
keywords: "infosec,information,security,blueteam,defense,enterprise,risk"
owner: "Braxton Ehle"
logo_path: "/images/itunes.png"
category: "Technology"
subcategory: "Tech News"
# Must be 'yes' or 'clean'
explicit_rating: clean
