# Site settings
title: Sound Security Podcast 
email: soundsecurity@braxtonehle.com
description: "Braxton Ehle and Osman Surkatty rant about the latest in information security news to help enterprises and mere mortals defend their information."
baseurl: ""
url: "http://soundsecurity.io"
username: "braxtone"
twitter_username: "soundsec"
gitrepo: "https://github.com/braxtone/soundsecurity.braxtonehle.com"

# Build settings
markdown: kramdown
permalink: pretty
show_drafts: null

exclude: [
          "LICENSE", 
          "README.md", 
          "bin/", 
          "_drafts/1969-07-16-template.markdown", 
          "s3_website.yml", 
          "spec/",
          "Rakefile",
          "Gemfile*"
         ]
